[package]
name = "gemma_tokenizer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
once_cell = "1.19"
tokenizers = { version = "0.20", default-features = false, features = ["unstable_wasm"] }
wasm-bindgen = "0.2"
js-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }
